const ANNUAL_PRICE_USD = 49;

export const ANNUAL_PRICE_DISPLAY = `$${ANNUAL_PRICE_USD}`;

export const MONTHLY_EQUIVALENT_DISPLAY = `$${(ANNUAL_PRICE_USD / 12).toFixed(2)}`;

export const SUBSCRIBE_CTA_LABEL = `Subscribe — ${MONTHLY_EQUIVALENT_DISPLAY}/month`;
