export {
	APPLE_APP_ID,
	APPLE_ITUNES_APP_META,
	appStoreUrl,
	CHROME_STORE_URL,
	CLIENT_CATEGORIES,
	clientCategoryOfGroup,
	clientNameForBuiltInOAuthClientId,
	IPHONE_APP_STORE_URL,
	clientGroupsInCategory,
	isBuiltInOAuthClientId,
	isClientName,
	SUPPORTED_CLIENTS,
} from "./supported-clients";
export type {
	AuthIdentity,
	BuiltInClientName,
	BuiltInOAuthClientId,
	ClientCategory,
	ClientGroup,
	ClientGroupInCategory,
	ClientInGroup,
	ClientName,
	ClientNameInCategory,
	ClientNameInGroup,
	InstallSource,
	SupportedClient,
} from "./supported-clients";
