const DAY_MS = 24 * 60 * 60 * 1000;

const FLUSH_TICK_TOLERANCE_MS = 30 * 60 * 1000;

const QUEUE_DIGEST_INTERVAL_DAYS = 7;

export const QUEUE_DIGEST_MIN_SAVE_AGE_DAYS = 30;

export const QUEUE_DIGEST_MIN_GAP_MS = QUEUE_DIGEST_INTERVAL_DAYS * DAY_MS - FLUSH_TICK_TOLERANCE_MS;

export const QUEUE_DIGEST_MIN_SAVE_AGE_MS = QUEUE_DIGEST_MIN_SAVE_AGE_DAYS * DAY_MS;
