import type { ArticleTopic } from "@packages/domain/article";

export type {
	ArticleFreshnessData,
	BumpArticleSavedAt,
	BumpArticleSavedAtParams,
	CountArticlesByUser,
	CountArticlesQuery,
	DeleteArticle,
	DigestCandidate,
	DigestEmailFilter,
	DigestPageCursor,
	FindArticleById,
	FindArticleByUrl,
	FindArticleFreshness,
	FindArticleUrlById,
	FindArticlesByUser,
	FindArticlesQuery,
	FindArticlesResult,
	FindUnreadSavesForDigest,
	FindUserArticlesByUrl,
	GlobalArticleData,
	MarkArticleViewed,
	MarkReaderReadyEmailSent,
	SaveArticle,
	SaveArticleGlobally,
	SaveArticleGloballyParams,
	SaveArticleParams,
	SortField,
	SortOrder,
	UnreadSavesForDigestPage,
	UpdateArticleStatus,
	UserArticleByUrl,
} from "@packages/provider-contracts/article-store";

export type FindArticleTopics = (url: string) => Promise<readonly ArticleTopic[]>;
