export const RELATED_CANDIDATES_MAX = 1000;
export const RELATED_RESULTS_MAX = 3;
export const RELATED_CANDIDATE_TEXT_MAX_CHARS = 300;
export const RELATED_REASON_MAX_CHARS = 120;
export const RELATED_MAX_OUTPUT_TOKENS = 1024;
